# Generated by Django 6.0.6 on 2026-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_device_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='buy_link',
            field=models.URLField(blank=True),
        ),
    ]
