# Generated by Django 6.0.6 on 2026-06-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
