# Generated by Django 6.0.6 on 2026-06-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_device_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
