# Generated by Django 6.0.6 on 2026-07-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='availability',
            field=models.CharField(default='In Stock', max_length=30),
        ),
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
