# Generated by Django 6.0.6 on 2026-08-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_device_availability_device_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated keywords like blind, wheelchair, elderly, hearing', max_length=300),
        ),
    ]
